### ISSUE TITLE
$HOD_LOCALWORKDIR not defined in environment of script submitted with 'hod batch'

### ISSUE THREAD

**Issue by boegel** [hpcugent/hanythingondemand#115]

**Comment by ehiggs** [comment]
This is defined by `hod connect`. The intention is that `HOD_LOCALWORKDIR` is for inspecting logs and configs. It wasn't intended for doing the work in a batch job.

Hadoop has a concept of a tmp dir so users shouldn't need to define one for that.

**Comment by boegel** [comment]
I was kind of expecting to be able to use $HOD_LOCALWORKDIR as a working directory in the script, but OK, I guess.

In the example for `hod batch` I'm not creating my own workdir, see http://boegel-hod.readthedocs.org/en/example_use_cases/Example_use_cases.html#id2.

So, closing for now, let's see if this pops up again later.
