### ISSUE TITLE
Spark 1.6

### ISSUE THREAD

**Issue by ehiggs** [hpcugent/hanythingondemand#142]
Spark 1.6 has been released and reflects a continuous improvement.

https://databricks.com/blog/2015/11/20/announcing-spark-1-6-preview-in-databricks.html
https://www.brighttalk.com/webcast/12891/181843

**Comment by boegel** [comment]
PR for easyconfig https://github.com/hpcugent/easybuild-easyconfigs/pull/2274 is merged

**Comment by ehiggs** [comment]
Done in #146
