### ISSUE TITLE
Support -W x=FLAGS:ADVRES:<reservation-name> flag

### ISSUE THREAD

**Issue by ehiggs** [hpcugent/hanythingondemand#147]
Support -W x=FLAGS:ADVRES:<reservation-name> flag. This is used to submit a hod job to a specific reservation so moab doesn't need to figure it out otherwise.

**Comment by ehiggs** [comment]
This has lowish priority since users can use `qalter <jobname> -W x=ADVRES:<reservation-name>` to move it into their reservation.

**Comment by ehiggs** [comment]
If we migrate to gc3pie then we will get whatever gc3pie uses. Or users will have to use `qalter`.

**Comment by boegel** [comment]
Hold on... Supporting GC3Pie doesn't mean we should leave the `pbs_python` support crippled.

Especially since we're nowhere near GC3Pie.

Implementing support for this isn't that difficult...
