### ISSUE TITLE
hod-readthedocs: section "command line interface"

### ISSUE THREAD

**Issue by epauwels** [hpcugent/hanythingondemand#174]
* Integrate dedicated page about --job options (see https://hod.readthedocs.io/en/latest/CLI_job_options.html#cmdline-job-options) more visibly into the documentation. Currently it is very well hidden behind a link. Separate anchor inside the document?
* There is also an error in this particular page
--job-nodes
The number of (full) workernodes to request for the job being submitted (default: *1*).
(The default is 1 and not 5, as it is mention now)

**Comment by boegel** [comment]
fixed in #179
