### ISSUE TITLE
Tidy up command line processing

### ISSUE THREAD

**Issue by ehiggs** [hpcugent/hanythingondemand#19]
Currently if you omit a required argument like `--config-config` then hod spits out some incoherent message that has nothing to do with the fact that the configuration file is missing. This needs to be fixed.

**Comment by ehiggs** [comment]
#33

**Comment by ehiggs** [comment]
This was fixed in #33.

**Comment by boegel** [comment]
I disagree, I don't think we should consider this fixed until we've matched what we're outlining in #43.

**Comment by boegel** [comment]
we've met the target set in #43, closing
