### ISSUE TITLE
Accessing web services is a really poor experience.

### ISSUE THREAD

**Issue by ehiggs** [hpcugent/hanythingondemand#2]
The web services for Hadoop are a big part of the attraction. However accessing the web services is a big pain in the backside since it involves setting up ssh tunnelling and so on. It's enough to make a user go mad.

We need to come up with a way to make this significantly easier.

Unfortunately this issue does not yet have a milestone or deliverable whereby we can currently know when it's done.

**Comment by boegel** [comment]
We have good documentation on this now at http://hod.readthedocs.org/en/latest/Connecting_to_web_UIs.html, and we managed to simplify the procedure a bit too (you can now use https://localhost:8888 as URL in your browser after setting up the tunnel and the proxy).

As far as I can tell, we can't make this much easier than it is now?
