### ISSUE TITLE
clean up workdir to avoid issues

### ISSUE THREAD

**Issue by boegel** [hpcugent/hanythingondemand#34]
Running multiple HOD jobs in parallel may lead to problems with the workdir:

```
error:
Caused by: org.apache.hadoop.fs.FSError: java.io.IOException: Disk quota
exceeded
         at
org.apache.hadoop.fs.RawLocalFileSystem$LocalFSFileOutputStream.write(RawLocalFileSystem.java:221)
         at
java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
         at
java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
         at java.io.FilterOutputStream.flush(FilterOutputStream.java:140)
         at java.io.DataOutputStream.flush(DataOutputStream.java:123)
         at java.io.FilterOutputStream.flush(FilterOutputStream.java:140)
         at java.io.FilterOutputStream.flush(FilterOutputStream.java:140)
         at java.io.DataOutputStream.flush(DataOutputStream.java:123)
         at org.apache.hadoop.mapred.IFile$Writer.close(IFile.java:163)
         at
org.apache.hadoop.mapreduce.task.reduce.MergeManagerImpl.finalMerge(MergeManagerImpl.java:739)
         at
org.apache.hadoop.mapreduce.task.reduce.MergeManagerImpl.close(MergeManagerImpl.java:363)
         at
org.apache.hadoop.mapreduce.task.reduce.Shuffle.run(Shuffle.java:158)
         ... 6 more
Caused by: java.io.IOException: Disk quota exceeded
         at java.io.FileOutputStream.writeBytes(Native Method)
         at java.io.FileOutputStream.write(FileOutputStream.java:345)
         at
org.apache.hadoop.fs.RawLocalFileSystem$LocalFSFileOutputStream.write(RawLocalFileSystem.java:219)
         ... 17 more
```

**Comment by ehiggs** [comment]
I'm not sure anything can be done by hod to fix users' issues with disk quota.

**Comment by boegel** [comment]
But HOD can clean up the logs?

I guess this is part supporting a nicer way of destroying an HOD cluster, and properly cleaning up while doing so.

**Comment by ehiggs** [comment]
Ok. I think this can be done when we have a `~/.config/hod/<jobid>/env dir we can figure out which directories belong to the job and blat them when we're done. That's actually really useful since it also trims where logs can hide.

**Comment by boegel** [comment]
Are you saying logs should go there too? Is it a good idea to store logs in `$HOME`, which is typically small/slow on our systems?

**Comment by ehiggs** [comment]
No I'm not saying logs go tin `$HOME`. I'm saying the hod workdir can be stored in `$HOME` so it can be cleared out. Then, if someone does a top level grep for logs on a parallel file system they aren't also grepping through old logs.

**Comment by boegel** [comment]
OK, thanks for clarifying that.

**Comment by ehiggs** [comment]
#95 implements this.

**Comment by boegel** [comment]
see #95 (one issue is enough ;))
