### ISSUE TITLE
HOD only works when it's installed as a module

### ISSUE THREAD

**Issue by boegel** [hpcugent/hanythingondemand#36]
Currently, HOD requires that either:

* `$EBMODNAMEHANYTHINGONDEMAND` is defined with the module name under which HOD is available
* or, that the `hanythingondemand` module was loaded with Tcl/C environment modules, i.e., that the `hanythingondemand` module name is listed in `$LOADEDMODULES`

This is rather clunky, and could probably be relaxed a bit. The only thing that is really needed is figuring out how `$PYTHONPATH` should be set, and which dependency modules should be loaded.

**Comment by ehiggs** [comment]
We kinda baked this in with `--hod-module`. But at least it's now specified rather than detected. If we're happy with `--hod-module` I think we can close this since we've implemented something that appears to be diametrically opposed.

**Comment by boegel** [comment]
The code that this issue refer to is removed in the PR for `--hod-module` (see #70), so let's close this since it's basically a duplicate now
