### ISSUE TITLE
hod dist doesn't work if we start the python process from `hod.main`

### ISSUE THREAD

**Issue by ehiggs** [hpcugent/hanythingondemand#53]
hod dist doesn't work if we start the python process from `hod.main`.

`hod dist` looks at the top level executable (within the python process) to determine where the etc dir is. Since `hod.main` was moved into the hod tree and out of bin, it can no longer find the dists.

**Comment by boegel** [comment]
I guess we'll need to require that `$HOD_ETCDIR` is defined?

In general, we can't derive the location of `etc` from the location of `hod/main.py` or `bin/hod`

The good thing is that we can handle this in the `hanythingondemand` module, a user will/should never notice.

**Comment by ehiggs** [comment]
I have a fix using pkg_resources. PR coming.
