### ISSUE TITLE
add support for --hod-module

### ISSUE THREAD

**Issue by boegel** [hpcugent/hanythingondemand#63]
With a configuration option like `--hod-module` in place, we can dance around the problem we have where a Python module that works on the login nodes running SL6 must be loaded first before defining the environment such that an HOD cluster can be submitted to CentOS7 clusters.

On the login nodes, it would suffice having an HOD active that uses the system Python; only `pbs_python` needs to be available.

Via `--hod-module`, the `hanythingondemand` module to be loaded in the job being submitted can be specified. This module needs to be built on top of a Python module that provides `netifaces`, `netaddr`, and `mpi4py`, besides having other compatible modules for Hadoop, Spark, IPython, etc.

This would also result in fixing #36.

**Comment by ehiggs** [comment]
>On the login nodes, it would suffice having an HOD active that uses the system Python; only pbs_python needs to be available.

That would mean we need to support system python which could be v. old. 

Maybe instead of `--hod-module` we support '--cluster' which sends the command to a particular cluster.

**Comment by boegel** [comment]
We only need to support system Python (requiring 2.6 is fine imho) for a small part of the code, i.e. the part where the job gets submitted. That's doable imho.

`--cluster` would require including site-specific stuff in the code? Sounds like a bad idea to me...

**Comment by ehiggs** [comment]
#70 supports this.

**Comment by boegel** [comment]
see #70
