### ISSUE TITLE
Make create/relabel check whether label is not in use already

### ISSUE THREAD

**Issue by ehiggs** [hpcugent/hanythingondemand#64]
`create` doesn't check if a label is in use. It should check whether label is not in use already and refuse to use the same label a second time.

**Comment by ehiggs** [comment]
There are a few cases to consider here:

1. A Job is running with the label :arrow_forward: Refuse to start a new one.
2. No job is running but a label exists (from a previous job) :arrow_forward: Refuse to start a new one (?)
3. A job has been submitted, but not started with the label :arrow_forward: Refuse to start a new one.

**Comment by boegel** [comment]
A label that is in use should never be reused; we can include a message that previous labels can be made available again via `hod cleanup`

**Comment by ehiggs** [comment]
#88 implements this.
