### ISSUE TITLE
Configuration page needs a touch up

### ISSUE THREAD

**Issue by ehiggs** [hpcugent/hanythingondemand#72]
Configuration documentation is missing a title and the first code example is missing a nice little box like we have with other code examples.

**Comment by ehiggs** [comment]
@boegel implemented this a while back.

**Comment by boegel** [comment]
http://hod.readthedocs.org/en/latest/Configuration.html still needs work, see `hod-genconfig` in the example

**Comment by ehiggs** [comment]
Fixed by #85 commit da38e13159d72cf8b1013fd633e0414edd346ab1
