### ISSUE TITLE
HOD module should be loaded in 'hod connect' environment?

### ISSUE THREAD

**Issue by boegel** [hpcugent/hanythingondemand#80]
so commands like `hod list` work there too (it's kind of weird if it doesn't)

**Comment by ehiggs** [comment]
I don't think it's required. If you want hod loaded, `module load hanythingondemand`. If the user wants to use a python different from the one they use for hanythingondemand then it's an issue.

**Comment by boegel** [comment]
Well, then maybe at least set an environment variable `$HOD_MODULE` so you can easily load the correct module (i.e. the one that is in use by the cluster)?

**Comment by ehiggs** [comment]
Thinking about this further, I think this risks conflicts. e.g. If you run `hod` using Python 2 but in your IPython notebook you want Python 3, then this will break.

**Comment by boegel** [comment]
We can revisit this later if people are confused about not having `hod` available after `hod connect`.
