### ISSUE TITLE
hod clone  - clones a dist in a target directory

### ISSUE THREAD

**Issue by ehiggs** [hpcugent/hanythingondemand#97]
We would like to use zipped eggs for deployment since it means shared file systems are abused less on startup (meaning we will have better interactivity). However, if the `etc` dir is zipped it makes it harder for people to make new hodconf distributions based on an existing dist. Therefore, we want a `hod clone` command as follows:

`hod clone --dist=<some-dist> --output-dir=<some-output-dir>`

`--dist` and `--output-dir` are non positional required arguments. This will copy the contents of the `<some-dist>` to `<some-output-dir>`.

**Comment by boegel** [comment]
fixed with #100
